### ISSUE TITLE
error while loading shared libraries: libmng.so.1: 

### ISSUE THREAD

**Issue by hakonhagland** [mviereck/kaptain#3]
I am trying to install `kaptain` on Ubuntu 20.04:

```
$ wget  https://github.com/mviereck/kaptain/raw/master/kaptain_0.73-3-staticqt4_amd64_debian.deb
$ sudo apt-get install ./kaptain_0.73-3-staticqt4_amd64_debian.deb
$ sudo apt-get install libjpeg62 libmng-dev
$ kaptain --help
kaptain: error while loading shared libraries: libmng.so.1: cannot open shared object file: No such file or directory
$ dpkg -L libmng-dev | grep so
/usr/lib/x86_64-linux-gnu/libmng.so
```
Note the difference in the names `libmng.so.1` and the installed version is `libmng.so`

**Comment by hakonhagland** [comment]
See also [How to solve missing libmng.so.1 in Trusty (14.04) Package is no more available](https://askubuntu.com/q/453452/156688)

**Comment by mviereck** [comment]
Thank you for the bug report!

I've added `configure` option `-no-libmng` in the Dockerfile to build the deb package. Now I am rebuilding the image. Hopefully that will fix the issue.
I'll reply here again once the build is finished and uploaded.

`libmng` serves to show some sort of animation and should not be needed for x11docker-gui use cases.

**Comment by mviereck** [comment]
I've uploaded a new static build: https://github.com/mviereck/kaptain/blob/master/kaptain_0.73-4-staticqt4_amd64_debian.deb

So far it works here on Debian testing. Please try out if that fixes the issue.
